apiVersion: apps/v1
kind: Deployment
metadata:
  name: nibiru
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nibiru
  template:
    metadata:
      labels:
        name: nibiru
    spec:
      serviceAccountName: nibiru
      containers:
        - name: nibiru
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - nibiru
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nibiru"
